### ISSUE TITLE
--use-only-cache is throwing errors

### ISSUE THREAD

**Issue by michaelarnauts** [tvgrabbers/tvgrabpyAPI#34]
Using latest code from git and I've just enabled the flemish tv channels and ran a `/usr/bin/tv_grab_nl3.py`. Next, when I run `/usr/bin/tv_grab_nl3.py --use-only-cache`, I get the following errors:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_fetch.py", line 1985, in __init__
    self.language = self.source_data['language']
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_fetch.py", line 1985, in __init__
    self.language = self.source_data['language']
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_fetch.py", line 1985, in __init__
    self.language = self.source_data['language']
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_fetch.py", line 1985, in __init__
    self.language = self.source_data['language']
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_fetch.py", line 1985, in __init__
    self.language = self.source_data['language']
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_fetch.py", line 1985, in __init__
    self.language = self.source_data['language']
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_fetch.py", line 1985, in __init__
    self.language = self.source_data['language']
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_fetch.py", line 1985, in __init__
    self.language = self.source_data['language']
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_fetch.py", line 1985, in __init__
    self.language = self.source_data['language']
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_fetch.py", line 1985, in __init__
    self.language = self.source_data['language']
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_fetch.py", line 1985, in __init__
    self.language = self.source_data['language']
TypeError: 'NoneType' object has no attribute '__getitem__'
No valid source description for 1 found. Disableing it!
No valid source description for 3 found. Disableing it!
No valid source description for 4 found. Disableing it!
No valid source description for 5 found. Disableing it!
No valid source description for 6 found. Disableing it!
No valid source description for 7 found. Disableing it!
No valid source description for 8 found. Disableing it!
No valid source description for 9 found. Disableing it!
No valid source description for 10 found. Disableing it!
No valid source description for 11 found. Disableing it!
No valid source description for 12 found. Disableing it!

An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_config.py", line 142, in grabber_main
    x = config.validate_commandline()
  File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_config.py", line 757, in validate_commandline
    self.write_opts_to_log()
  File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_config.py", line 2707, in write_opts_to_log
    log_array.append(u'  prime_source = %s (%s)\n' % (src_id, self.channelsource[src_id].source))
KeyError: -1

If you want assistence, please attach your configuration and log files!
     /config/.xmltv/tv_grab_nl3_py.conf
     /config/.xmltv/tv_grab_nl3_py.log
Waiting for all remaining threads to finish
Waiting for all remaining threads to finish
Verifying the database
```

LOG:
```
2018-08-27 16:20:24 UTC: Loaded the English texts file
2018-08-27 16:20:24 UTC: Using config file: /config/.xmltv/tv_grab_nl3_py.conf
2018-08-27 16:20:24 CEST: No valid source description for 1 found. Disableing it!
2018-08-27 16:20:24 CEST: No valid source description for 3 found. Disableing it!
2018-08-27 16:20:24 CEST: No valid source description for 4 found. Disableing it!
2018-08-27 16:20:24 CEST: No valid source description for 5 found. Disableing it!
2018-08-27 16:20:24 CEST: No valid source description for 6 found. Disableing it!
2018-08-27 16:20:24 CEST: No valid source description for 7 found. Disableing it!
2018-08-27 16:20:24 CEST: No valid source description for 8 found. Disableing it!
2018-08-27 16:20:24 CEST: No valid source description for 9 found. Disableing it!
2018-08-27 16:20:24 CEST: No valid source description for 10 found. Disableing it!
2018-08-27 16:20:24 CEST: No valid source description for 11 found. Disableing it!
2018-08-27 16:20:24 CEST: No valid source description for 12 found. Disableing it!
2018-08-27 16:20:24 CEST: An unexpected error has occured:
2018-08-27 16:20:24 CEST: Traceback (most recent call last):
2018-08-27 16:20:24 CEST:   File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_config.py", line 142, in grabber_main
2018-08-27 16:20:24 CEST:     x = config.validate_commandline()
2018-08-27 16:20:24 CEST:   File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_config.py", line 757, in validate_commandline
2018-08-27 16:20:24 CEST:     self.write_opts_to_log()
2018-08-27 16:20:24 CEST:   File "/usr/lib/python2.7/site-packages/tvgrabpyAPI/tv_grab_config.py", line 2707, in write_opts_to_log
2018-08-27 16:20:24 CEST:     log_array.append(u'  prime_source = %s (%s)\n' % (src_id, self.channelsource[src_id].source))
2018-08-27 16:20:24 CEST: KeyError: -1
2018-08-27 16:20:24 CEST: If you want assistence, please attach your configuration and log files!
2018-08-27 16:20:24 CEST:      /config/.xmltv/tv_grab_nl3_py.conf
2018-08-27 16:20:24 CEST:      /config/.xmltv/tv_grab_nl3_py.log
2018-08-27 16:20:24 CEST: Waiting for all remaining threads to finish
2018-08-27 16:20:25 CEST: Waiting for all remaining threads to finish
2018-08-27 16:20:25 CEST: Verifying the database
```

**Comment by hikavdh** [comment]
Which version and please a complete log and config file

**Comment by hikavdh** [comment]
To me it looks at first glance that you do not have the json source files. So next to the above; what is the content of ~/.xmltv/sources/?

**Comment by hikavdh** [comment]
OK, I see what's happening. Obviously nobody has used the use-only-cache option since the introduction of version 1.0.7 over a year ago, as this bug is introduced there with the conversion of the source-files.

**Comment by hikavdh** [comment]
And when I fixed that I discovered it conflicting withe the new "pre_merge" setting. So setting `--use-only-cache` now automatically disables "pre_merge"
https://github.com/tvgrabbers/tvgrabpyAPI/releases/tag/beta-1.0.9-p20180827-3
