### ISSUE TITLE
unsupported locale setting

### ISSUE THREAD

**Issue by macfreek** [tvgrabbers/tvgrabpyAPI#6]
I just got this error with Python 2.7.13:

{{{
Traceback (most recent call last):
  File "/Users/freek/Repository/tvgrabpyAPI/tv_grab_nl3.py", line 123, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
}}}

My recommendation is to change:
{{{
locale.setlocale(locale.LC_ALL, '')
}}}
into:
{{{
try:
    locale.setlocale(locale.LC_ALL, 'C.UTF-8')
except locale.Error:
    locale.setlocale(locale.LC_ALL, 'C')
}}}

**Comment by hikavdh** [comment]
That 's weird as all that command does is read in the by the system set locale. Does Mac not use UTF-8? 2.7.13 is not jet deemed stable by Gentoo, so I'm running 2.7.12.
